---
deployment:
  tasks:
    - export DEPLOYPATH=/home/memafetd/public_html # Specify the deployment path
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R catalog $DEPLOYPATH
    - /bin/cp -R extension $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R install $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R htaccess.txt $DEPLOYPATH
    - /bin/cp -R config.php $DEPLOYPATH
    - /bin/cp -R cron.php $DEPLOYPATH
    - /bin/cp -R error.html $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R install.lock $DEPLOYPATH
    - /bin/cp -R LICENSE $DEPLOYPATH
    - /bin/cp -R php.ini $DEPLOYPATH
    - /bin/cp -R robots.txt $DEPLOYPATH